### PR TITLE
Complete python gRPC requests when closing

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
+1

did you try the reload feature ?
I hope that this change doesn't break it.
Unfortunately it is to be tested manually, in order to see how it behaves for the user.

if we block waiting for the current response to complete and the application is broken then we don't want it to hang

**Comment by eolivelli** [comment]
Also it seems that you have to rebase on top of main branch

**Comment by cbornet** [comment]
I rebased and changed a bit the code.
The PR doesn't touch the `restart` procedure. It only affects the `close` and the tests.

**Comment by cbornet** [comment]
I tested the restart manually. Works fine.

**Pull request merged**
