### PR TITLE
Add Python logging with same format as Java

### LINKED ISSUE #346: Configure Python log format to be coherent with Java

### PR DESCRIPTION
**Pull request by cbornet**
Fix #346

### CODE REVIEW

**Review by nicoloboschi — COMMENTED** [review]
How the custom processor should call the logger?

**Comment by cbornet** [comment]
The processor can use logging.info or it's own logger. Eg:
```python
import logging
logging.info("hello") # uses the root logger

LOG = logging.getLogger(__name__) # uses a logger with the module name
LOG.info("world")
```

**Review by eolivelli — APPROVED** [review]
+1

we need to add a section to the docs here

**Comment by cbornet** [comment]
> we need to add a section to the docs here

Sure. Note that logging is built-in in Python. So there is no surprise here for Python devs.

**Pull request merged**
