### PR TITLE
Run black and ruff to lint the code

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by nicoloboschi — COMMENTED** [review]
1. this tool modifies  the code or just check the rules?
2. how do run it locally? can you add instructions ? 
3. do we need to add some checks in the CI?

**Comment by cbornet** [comment]
Currently it's running the checks during python tests.
I'll add some ant tasks to lint the code during generate-sources like we have for Java.

**Comment by cbornet** [comment]
I've added the linting to the generate-sources phase.
And a git status is done to check that the committed files are linted.

**Pull request merged**
