### PR TITLE
Fix gateway with Pulsar

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

The only thing that I am not sure is that on the Producer we enforce a String schema on the topic.
As the topic is in theory schemaless we should keep BYTES. But we can address it in a follow up work

**Comment by cbornet** [comment]
You're right. It should be BYTES.
The other concern I have is whether the read MessageId contains the info for all partitions.

**Comment by eolivelli** [comment]
We have to add test cases for partitioned topics. I guess we have to manually keep track of each partition

**Comment by cbornet** [comment]
> The only thing that I am not sure is that on the Producer we enforce a String schema on the topic.
As the topic is in theory schemaless we should keep BYTES

We can do like Kafka and wait for the first message to infer the schema type based on the Java type. I'll do it.

**Pull request merged**
